#General settings
dist: xenial
os: linux

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c

#Set the build environment
env:
  global:
    - INCLUDE=addons/sourcemod/scripting/include
    - SCRIPTING=addons/sourcemod/scripting
    - PLUGINS=addons/sourcemod/plugins
  jobs:
    - SMVERSION=1.9
    - SMVERSION=1.10
    - SMVERSION=1.11

jobs:
  allow_failures:
    - env: SMVERSION=1.11

install:
    # Sourcemod download
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - chmod +x $SCRIPTING/spcomp
    - mkdir $SCRIPTING/compiled
    - mkdir build
    - cp -R addons build
    - cp LICENSE build
script:
    - $SCRIPTING/spcomp -E -o$SCRIPTING'/compiled/VIP_Core' -v0 $SCRIPTING'/VIP_Core.sp'

#Release
before_deploy:
    - ls -lR
    - cp $SCRIPTING/compiled/VIP_Core.smx build/$PLUGINS
    - zip -rq VIP_Core.zip build
    - tar -czf VIP_Core.tar.gz build
deploy:
    provider: releases
    token: ${GH_TOKEN}
    file:
      - VIP_Core.zip
      - VIP_Core.tar.gz

#branches:
#  only:
#    - master
#    - dev
#    - /^v\d+\.\d+\.\d+.*$/
#Notifications
notifications:
    email: false
